config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "campains#index"

  resources :campains, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campains_controller.rb
class CampainsController < ApplicationController
  def index
    @campains = Unamo::GetData.campains
  rescue

  end

  def show
    @period = params['time_period'] || 'one_month'
    @keywords = Unamo::GetData.keywords(params[:id], @period.to_sym)
    @current_time = Unamo::TimeCalculator.current_time(@period.to_sym)
  end
end

app/views/campains/index.html.erb
<h2>List of all campaigns</h2>
<table class='table' style='width:100%; text-align: center;'>
  <thead class='thead-dark'>
    <tr>
      <th scope='col'></th>
      <th scope='col'>Title</th>
      <th scope='col' scope='col'>Id</th>
      <th scope='col' scope='col'></th>
    </tr>
  </thead>
  <% @campains.each_with_index do |campain, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= campain.title %></td>
      <td><%= campain.id %></td>
      <td><%= link_to 'Details', campain_path(campain.id) %></td>
    </tr>
  <% end %>
</table>

app/views/campains/show.html.erb
<h5 class="header">View keyword statistics for <%= @current_time %></h5>
<div class="to-right">
  <%= select_tag "time_period", options_for_select([["1 week", :one_week], ["2 weeks", :two_weeks], ["1 month", :one_month]], @period) %>
</div>

<table class='table' style='width:100%; text-align: center;'>
  <thead class='thead-dark'>
    <tr>
      <th scope='col'>Keyword</th>
      <th scope='col'>Best ranking</th>
      <th scope='col' scope='col'>Date of occurrnce</th>
      <th scope='col'>Worst ranking</th>
      <th scope='col'>Date of occurrnce</th>
      <th scope='col'>Mean ranking</th>
      <th scope='col'>Groups</th>
    </tr>
  </thead>

  <% @keywords.each do |keyword| %>
    <tr>
      <td><%= keyword.name %></td>
      <td><%= keyword.best_position %></td>
      <td><%= keyword.best_position_date %></td>
      <td><%= keyword.worst_position %></td>
      <td><%= keyword.worst_position_date %></td>
      <td><%= keyword.average_of_positions %></td>
      <td>
        <% keyword.groups.each do |group| %>
          <%= group %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>